/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'

import { Route as Process1Process1DepotDemandImport } from './routes/Process1/Process1DepotDemand'
import { Route as Process1Process1EncaissementTaxeImport } from './routes/Process1/Process1EncaissementTaxe'
import { Route as Process1Process1ExecutionImport } from './routes/Process1/Process1Execution'
import { Route as Process1Process1FinImport } from './routes/Process1/Process1Fin'
import { Route as Process1Process1LeverReserve2Import } from './routes/Process1/Process1LeverReserve2'
import { Route as Process1Process1LeverReserveFormeImport } from './routes/Process1/Process1LeverReserverForme'
import { Route as Process1Process1RefusDepotImport } from './routes/Process1/Process1RefusDepot'
import { Route as Process1Process1RefusEncaissementImport } from './routes/Process1/Process1RefusEncaissement'


import { Route as Process2Process2EmailEnvoyeImport } from './routes/Process2/Process2EmailEnvoye'
import { Route as Process2Process2EnregistrementDemandeImport } from './routes/Process2/Process2EnregistrementDemande'
import { Route as Process2Process2ExaminerFondImport } from './routes/Process2/Process2ExaminerFond'
import { Route as Process2Process2ImmatriculationProvisoireImport } from './routes/Process2/Process2ImmatriculationProvisoire'
import { Route as Process2Process2PréparerImmatriculationImport } from './routes/Process2/Process2PréparerImmatriculation'
import { Route as Process2Process2RejetProvisoireImport } from './routes/Process2/Process2RejetProvisoire'


import { Route as Process3Process3EmissionCC14Import } from './routes/Process3/Process3EmissionCC14'
import { Route as Process3Process3EnregistrementDemandeImport } from './routes/Process3/Process3EnregistrementDemande'
import { Route as Process3Process3EtablissementCC20Import } from './routes/Process3/Process3EtablissementCC20'
import { Route as Process3Process3EtablissementPR14Import } from './routes/Process3/Process3EtablissementPR14'
import { Route as Process3Process3FinProcessusImport } from './routes/Process3/Process3FinProcessus'
import { Route as Process3Process3PublicationPR14Import } from './routes/Process3/Process3PublicationPR14'
import { Route as Process3Process3TransmissionPR14Import } from './routes/Process3/Process3TransmissionPR14'
import { Route as Process3Process3TypeChangementImport } from './routes/Process3/Process3TypeChangement'
import { Route as Process3Process3VerificationFormeImport } from './routes/Process3/Process3VerificationForme'
import { Route as Process3Process3NotifierImport } from './routes/Process3/Process3Notifier'


// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const Process1Process1DepotDemandRoute =
  Process1Process1DepotDemandImport.update({
    id: '/Process1/Process1DepotDemand',
    path: '/Process1/Process1DepotDemand',
    getParentRoute: () => rootRoute,
  } as any)

const Process1Process1EncaissementTaxeRoute =
  Process1Process1EncaissementTaxeImport.update({
    id: '/Process1/Process1EncaissementTaxe',
    path: '/Process1/Process1EncaissementTaxe',
    getParentRoute: () => rootRoute,
  } as any)

const Process1Process1ExecutionRoute =
  Process1Process1ExecutionImport.update({
    id: '/Process1/Process1Execution',
    path: '/Process1/Process1Execution',
    getParentRoute: () => rootRoute,
  } as any)

const Process1Process1FinRoute =
  Process1Process1FinImport.update({
    id: '/Process1/Process1Fin',
    path: '/Process1/Process1Fin',
    getParentRoute: () => rootRoute,
  } as any)

const Process1Process1LeverReserve2Route =
  Process1Process1LeverReserve2Import.update({
    id: '/Process1/Process1LeverReserve2',
    path: '/Process1/Process1LeverReserve2',
    getParentRoute: () => rootRoute,
  } as any)

const Process1Process1LeverReserveFormeRoute =
  Process1Process1LeverReserveFormeImport.update({
    id: '/Process1/Process1LeverReserveForme',
    path: '/Process1/Process1LeverReserveForme',
    getParentRoute: () => rootRoute,
  } as any)

const Process1Process1RefusDepotRoute = Process1Process1RefusDepotImport.update(
  {
    id: '/Process1/Process1RefusDepot',
    path: '/Process1/Process1RefusDepot',
    getParentRoute: () => rootRoute,
  } as any,
)

const Process1Process1RefusEncaissementRoute =
  Process1Process1RefusEncaissementImport.update({
    id: '/Process1/Process1RefusEncaissement',
    path: '/Process1/Process1RefusEncaissement',
    getParentRoute: () => rootRoute,
  } as any)

const Process2Process2EmailEnvoyeRoute =
  Process2Process2EmailEnvoyeImport.update({
    id: '/Process2/Process2EmailEnvoye',
    path: '/Process2/Process2EmailEnvoye',
    getParentRoute: () => rootRoute,
  } as any)

const Process2Process2EnregistrementDemandeRoute = Process2Process2EnregistrementDemandeImport.update({
  id: '/Process2/Process2EnregistrementDemande',
  path: '/Process2/Process2EnregistrementDemande',
  getParentRoute: () => rootRoute,
} as any)

const Process2Process2ExaminerFondRoute = Process2Process2ExaminerFondImport.update({
  id: '/Process2/Process2ExaminerFond',
  path: '/Process2/Process2ExaminerFond',
  getParentRoute: () => rootRoute,
} as any)

const Process2Process2ImmatriculationProvisoireRoute = Process2Process2ImmatriculationProvisoireImport.update({
  id: '/Process2/Process2ImmatriculationProvisoire',
  path: '/Process2/Process2ImmatriculationProvisoire',
  getParentRoute: () => rootRoute,
} as any)

const Process2Process2PréparerImmatriculationRoute =
  Process2Process2PréparerImmatriculationImport.update({
    id: '/Process2/Process2PréparerImmatriculation',
    path: '/Process2/Process2PréparerImmatriculation',
    getParentRoute: () => rootRoute,
  } as any)

const Process2Process2RejetProvisoireRoute = Process2Process2RejetProvisoireImport.update({
  id: '/Process2/Process2RejetProvisoire',
  path: '/Process2/Process2RejetProvisoire',
  getParentRoute: () => rootRoute,
} as any)


const Process3Process3EmissionCC14Route = Process3Process3EmissionCC14Import.update(
  {
    id: '/Process3/Process3EmissionCC14Route',
    path: '/Process3/Process3EmissionCC14Route',
    getParentRoute: () => rootRoute,
  } as any,
)

const Process3Process3EnregistrementDemandeRoute =
  Process3Process3EnregistrementDemandeImport.update({
    id: '/Process3/Process3EnregistrementDemande',
    path: '/Process3/Process3EnregistrementDemande',
    getParentRoute: () => rootRoute,
  } as any)

const Process3Process3EtablissementCC20Route =
  Process3Process3EtablissementCC20Import.update({
    id: '/Process3/Process3EtablissementCC20',
    path: '/Process3/Process3EtablissementCC20',
    getParentRoute: () => rootRoute,
  } as any)

const Process3Process3EtablissementPR14Route = Process3Process3EtablissementPR14Import.update({
  id: '/Process3/Process3EtablissementPR14',
  path: '/Process3/Process3EtablissementPR14',
  getParentRoute: () => rootRoute,
} as any)

const Process3Process3FinProcessusRoute = Process3Process3FinProcessusImport.update({
  id: '/Process3/Process3FinProcessus',
  path: '/Process3/Process3FinProcessus',
  getParentRoute: () => rootRoute,
} as any)

const Process3Process3PublicationPR14Route = Process3Process3PublicationPR14Import.update({
  id: '/Process3/Process3PublicationPR14',
  path: '/Process3/Process3PublicationPR14',
  getParentRoute: () => rootRoute,
} as any)

const Process3Process3TransmissionPR14Route =
  Process3Process3TransmissionPR14Import.update({
    id: '/Process3/Process3TransmissionPR14',
    path: '/Process3/Process3TransmissionPR14',
    getParentRoute: () => rootRoute,
  } as any)

const Process3Process3TypeChangementRoute = Process3Process3TypeChangementImport.update({
  id: '/Process3/Process3TypeChangement',
  path: '/Process3/Process3TypeChangement',
  getParentRoute: () => rootRoute,
} as any)

const Process3Process3VerificationFormeRoute = Process3Process3VerificationFormeImport.update({
  id: '/Process3/Process3VerificationForme',
  path: '/Process3/Process3VerificationForme',
  getParentRoute: () => rootRoute,
} as any)

const Process3Process3NotifierRoute = Process3Process3NotifierImport.update({
  id: '/Process3/Process3Notifier',
  path: '/Process3/Process3Notifier',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/Process1/Process1DepotDemand': {
      id: '/Process1/Process1DepotDemand'
      path: '/Process1/Process1DepotDemand'
      fullPath: '/Process1/Process1DepotDemand'
      preLoaderRoute: typeof Process1Process1DepotDemandImport
      parentRoute: typeof rootRoute
    }
    '/Process1/Process1EncaissementTaxe': {
      id: '/Process1/Process1EncaissementTaxe'
      path: '/Process1/Process1EncaissementTaxe'
      fullPath: '/Process1/Process1EncaissementTaxe'
      preLoaderRoute: typeof Process1Process1EncaissementTaxeImport
      parentRoute: typeof rootRoute
    }
    '/Process1/Process1Execution': {
      id: '/Process1/Process1Execution'
      path: '/Process1/Process1Execution'
      fullPath: '/Process1/Process1Execution'
      preLoaderRoute: typeof Process1Process1ExecutionImport
      parentRoute: typeof rootRoute
    }
    '/Process1/Process1Fin': {
      id: '/Process1/Process1Fin'
      path: '/Process1/Process1Fin'
      fullPath: '/Process1/Process1Fin'
      preLoaderRoute: typeof Process1Process1FinImport
      parentRoute: typeof rootRoute
    }
    '/Process1/Process1LeverReserve2': {
      id: '/Process1/Process1LeverReserve2'
      path: '/Process1/Process1LeverReserve2'
      fullPath: '/Process1/Process1LeverReserve2'
      preLoaderRoute: typeof Process1Process1LeverReserve2Import
      parentRoute: typeof rootRoute
    }
    '/Process1/Process1LeverReserveForme': {
      id: '/Process1/Process1LeverReserveForme'
      path: '/Process1/Process1LeverReserveForme'
      fullPath: '/Process1/Process1LeverReserveForme'
      preLoaderRoute: typeof Process1Process1LeverReserveFormeImport
      parentRoute: typeof rootRoute
    }
    '/Process1/Process1RefusDepot': {
      id: '/Process1/Process1RefusDepot'
      path: '/Process1/Process1RefusDepot'
      fullPath: '/Process1/Process1RefusDepot'
      preLoaderRoute: typeof Process1Process1RefusDepotImport
      parentRoute: typeof rootRoute
    }
    '/Process1/Process1RefusEncaissement': {
      id: '/Process1/Process1RefusEncaissement'
      path: '/Process1/Process1RefusEncaissement'
      fullPath: '/Process1/Process1RefusEncaissement'
      preLoaderRoute: typeof Process1Process1RefusEncaissementImport
      parentRoute: typeof rootRoute
    }
    '/Process2/Process2EmailEnvoye': {
      id: '/Process2/Process2EmailEnvoye'
      path: '/Process2/Process2EmailEnvoye'
      fullPath: '/Process2/Process2EmailEnvoye'
      preLoaderRoute: typeof Process2Process2EmailEnvoyeImport
      parentRoute: typeof rootRoute
    }
    '/Process2/Process2EnregistrementDemande': {
      id: '/Process2/Process2EnregistrementDemande'
      path: '/Process2/Process2EnregistrementDemande'
      fullPath: '/Process2/Process2EnregistrementDemande'
      preLoaderRoute: typeof Process2Process2EnregistrementDemandeImport
      parentRoute: typeof rootRoute
    }
    '/Process2/Process2ExaminerFond': {
      id: '/Process2/Process2ExaminerFond'
      path: '/Process2/Process2ExaminerFond'
      fullPath: '/Process2/Process2ExaminerFond'
      preLoaderRoute: typeof Process2Process2ExaminerFondImport
      parentRoute: typeof rootRoute
    }
    '/Process2/Process2ImmatriculationProvisoire': {
      id: '/Process2/Process2ImmatriculationProvisoire'
      path: '/Process2/Process2ImmatriculationProvisoire'
      fullPath: '/Process2/Process2ImmatriculationProvisoire'
      preLoaderRoute: typeof Process2Process2ImmatriculationProvisoireImport
      parentRoute: typeof rootRoute
    }
    '/Process2/Process2PréparerImmatriculation': {
      id: '/Process2/Process2PréparerImmatriculation'
      path: '/Process2/Process2PréparerImmatriculation'
      fullPath: '/Process2/Process2PréparerImmatriculation'
      preLoaderRoute: typeof Process2Process2PréparerImmatriculationImport
      parentRoute: typeof rootRoute
    }
    '/Process2/Process2RejetProvisoire': {
      id: '/Process2/Process2RejetProvisoire'
      path: '/Process2/Process2RejetProvisoire'
      fullPath: '/Process2/Process2RejetProvisoire'
      preLoaderRoute: typeof Process2Process2RejetProvisoireImport
      parentRoute: typeof rootRoute
    }
    '/Process3/Process3EmissionCC14': {
      id: '/Process3/Process3EmissionCC14'
      path: '/Process3/Process3EmissionCC14'
      fullPath: '/Process3/Process3EmissionCC14'
      preLoaderRoute: typeof Process3Process3EmissionCC14Import
      parentRoute: typeof rootRoute
    }
    '/Process3/Process3EnregistrementDemande': {
      id: '/Process3/Process3EnregistrementDemande'
      path: '/Process3/Process3EnregistrementDemande'
      fullPath: '/Process3/Process3EnregistrementDemande'
      preLoaderRoute: typeof Process3Process3EnregistrementDemandeImport
      parentRoute: typeof rootRoute
    }
    '/Process3/Process3EtablissementCC20': {
      id: '/Process3/Process3EtablissementCC20'
      path: '/Process3/Process3EtablissementCC20'
      fullPath: '/Process3/Process3EtablissementCC20'
      preLoaderRoute: typeof Process3Process3EtablissementCC20Import
      parentRoute: typeof rootRoute
    }
    '/Process3/Process3EtablissementPR14': {
      id: '/Process3/Process3EtablissementPR14'
      path: '/Process3/Process3EtablissementPR14'
      fullPath: '/Process3/Process3EtablissementPR14'
      preLoaderRoute: typeof Process3Process3EtablissementPR14Import
      parentRoute: typeof rootRoute
    }
    '/Process3/Process3FinProcessus': {
      id: '/Process3/Process3FinProcessus'
      path: '/Process3/Process3FinProcessus'
      fullPath: '/Process3/Process3FinProcessus'
      preLoaderRoute: typeof Process3Process3FinProcessusImport
      parentRoute: typeof rootRoute
    }
    '/Process3/Process3PublicationPR14': {
      id: '/Process3/Process3PublicationPR14'
      path: '/Process3/Process3PublicationPR14'
      fullPath: '/Process3/Process3PublicationPR14'
      preLoaderRoute: typeof Process3Process3PublicationPR14Import
      parentRoute: typeof rootRoute
    }
    '/Process3/Process3TransmissionPR14': {
      id: '/Process3/Process3TransmissionPR14'
      path: '/Process3/Process3TransmissionPR14'
      fullPath: '/Process3/Process3TransmissionPR14'
      preLoaderRoute: typeof Process3Process3TransmissionPR14Import
      parentRoute: typeof rootRoute
    }
    '/Process3/Process3TypeChangement': {
      id: '/Process3/Process3TypeChangement'
      path: '/Process3/Process3TypeChangement'
      fullPath: '/Process3/Process3TypeChangement'
      preLoaderRoute: typeof Process3Process3TypeChangementImport
      parentRoute: typeof rootRoute
    }
    '/Process3/Process3VerificationForme': {
      id: '/Process3/Process3VerificationForme'
      path: '/Process3/Process3VerificationForme'
      fullPath: '/Process3/Process3VerificationForme'
      preLoaderRoute: typeof Process3Process3VerificationFormeImport
      parentRoute: typeof rootRoute
    }
    '/Process3/Process3Notifier': {
      id: '/Process3/Process3Notifier'
      path: '/Process3/Process3Notifier'
      fullPath: '/Process3/Process3Notifier'
      preLoaderRoute: typeof Process3Process3NotifierImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/Process1/Process1DepotDemand': typeof Process1Process1DepotDemandRoute
  '/Process1/Process1EncaissementTaxe': typeof Process1Process1EncaissementTaxeRoute
  '/Process1/Process1Execution': typeof Process1Process1ExecutionRoute
  '/Process1/Process1Fin': typeof Process1Process1FinRoute
  '/Process1/Process1LeverReserve2': typeof Process1Process1LeverReserve2Route
  '/Process1/Process1LeverReserveForme': typeof Process1Process1LeverReserveFormeRoute
  '/Process1/Process1RefusDepot': typeof Process1Process1RefusDepotRoute
  '/Process1/Process1RefusEncaissement': typeof Process1Process1RefusEncaissementRoute

  '/Process2/Process2EmailEnvoye': typeof Process2Process2EmailEnvoyeRoute
  '/Process2/Process2EnregistrementDemande': typeof Process2Process2EnregistrementDemandeRoute
  '/Process2/Process2ExaminerFond': typeof Process2Process2ExaminerFondRoute
  '/Process2/Process2ImmatriculationProvisoire': typeof Process2Process2ImmatriculationProvisoireRoute
  '/Process2/Process2PréparerImmatriculation': typeof Process2Process2PréparerImmatriculationRoute
  '/Process2/Process2RejetProvisoire': typeof Process2Process2RejetProvisoireRoute

  '/Process3/Process3EmissionCC14': typeof Process3Process3EmissionCC14Route
  '/Process3/Process3EnregistrementDemande': typeof Process3Process3EnregistrementDemandeRoute
  '/Process3/Process3EtablissementCC20': typeof Process3Process3EtablissementCC20Route
  '/Process3/Process3EtablissementPR14': typeof Process3Process3EtablissementPR14Route
  '/Process3/Process3FinProcessus': typeof Process3Process3FinProcessusRoute
  '/Process3/Process3PublicationPR14': typeof Process3Process3PublicationPR14Route
  '/Process3/Process3TransmissionPR14': typeof Process3Process3TransmissionPR14Route
  '/Process3/Process3TypeChangement': typeof Process3Process3TypeChangementRoute
  '/Process3/Process3VerificationForme': typeof Process3Process3VerificationFormeRoute
  '/Process3/Process3Notifier': typeof Process3Process3NotifierRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/Process1/Process1DepotDemand': typeof Process1Process1DepotDemandRoute
  '/Process1/Process1EncaissementTaxe': typeof Process1Process1EncaissementTaxeRoute
  '/Process1/Process1Execution': typeof Process1Process1ExecutionRoute
  '/Process1/Process1Fin': typeof Process1Process1FinRoute
  '/Process1/Process1LeverReserve2': typeof Process1Process1LeverReserve2Route
  '/Process1/Process1LeverReserveForme': typeof Process1Process1LeverReserveFormeRoute
  '/Process1/Process1RefusDepot': typeof Process1Process1RefusDepotRoute
  '/Process1/Process1RefusEncaissement': typeof Process1Process1RefusEncaissementRoute

  '/Process2/Process2EmailEnvoye': typeof Process2Process2EmailEnvoyeRoute
  '/Process2/Process2EnregistrementDemande': typeof Process2Process2EnregistrementDemandeRoute
  '/Process2/Process2ExaminerFond': typeof Process2Process2ExaminerFondRoute
  '/Process2/Process2ImmatriculationProvisoire': typeof Process2Process2ImmatriculationProvisoireRoute
  '/Process2/Process2PréparerImmatriculation': typeof Process2Process2PréparerImmatriculationRoute
  '/Process2/Process2RejetProvisoire': typeof Process2Process2RejetProvisoireRoute

  '/Process3/Process3EmissionCC14': typeof Process3Process3EmissionCC14Route
  '/Process3/Process3EnregistrementDemande': typeof Process3Process3EnregistrementDemandeRoute
  '/Process3/Process3EtablissementCC20': typeof Process3Process3EtablissementCC20Route
  '/Process3/Process3EtablissementPR14': typeof Process3Process3EtablissementPR14Route
  '/Process3/Process3FinProcessus': typeof Process3Process3FinProcessusRoute
  '/Process3/Process3PublicationPR14': typeof Process3Process3PublicationPR14Route
  '/Process3/Process3TransmissionPR14': typeof Process3Process3TransmissionPR14Route
  '/Process3/Process3TypeChangement': typeof Process3Process3TypeChangementRoute
  '/Process3/Process3VerificationForme': typeof Process3Process3VerificationFormeRoute
  '/Process3/Process3Notifier': typeof Process3Process3NotifierRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/Process1/Process1DepotDemand': typeof Process1Process1DepotDemandRoute
  '/Process1/Process1EncaissementTaxe': typeof Process1Process1EncaissementTaxeRoute
  '/Process1/Process1Execution': typeof Process1Process1ExecutionRoute
  '/Process1/Process1Fin': typeof Process1Process1FinRoute
  '/Process1/Process1LeverReserve2': typeof Process1Process1LeverReserve2Route
  '/Process1/Process1LeverReserveForme': typeof Process1Process1LeverReserveFormeRoute
  '/Process1/Process1RefusDepot': typeof Process1Process1RefusDepotRoute
  '/Process1/Process1RefusEncaissement': typeof Process1Process1RefusEncaissementRoute

  '/Process2/Process2EmailEnvoye': typeof Process2Process2EmailEnvoyeRoute
  '/Process2/Process2EnregistrementDemande': typeof Process2Process2EnregistrementDemandeRoute
  '/Process2/Process2ExaminerFond': typeof Process2Process2ExaminerFondRoute
  '/Process2/Process2ImmatriculationProvisoire': typeof Process2Process2ImmatriculationProvisoireRoute
  '/Process2/Process2PréparerImmatriculation': typeof Process2Process2PréparerImmatriculationRoute
  '/Process2/Process2RejetProvisoire': typeof Process2Process2RejetProvisoireRoute

  '/Process3/Process3EmissionCC14': typeof Process3Process3EmissionCC14Route
  '/Process3/Process3EnregistrementDemande': typeof Process3Process3EnregistrementDemandeRoute
  '/Process3/Process3EtablissementCC20': typeof Process3Process3EtablissementCC20Route
  '/Process3/Process3EtablissementPR14': typeof Process3Process3EtablissementPR14Route
  '/Process3/Process3FinProcessus': typeof Process3Process3FinProcessusRoute
  '/Process3/Process3PublicationPR14': typeof Process3Process3PublicationPR14Route
  '/Process3/Process3TransmissionPR14': typeof Process3Process3TransmissionPR14Route
  '/Process3/Process3TypeChangement': typeof Process3Process3TypeChangementRoute
  '/Process3/Process3VerificationForme': typeof Process3Process3VerificationFormeRoute
  '/Process3/Process3Notifier': typeof Process3Process3NotifierRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
  | '/'
  | '/Process1/Process1DepotDemand'
  | '/Process1/Process1EncaissementTaxe'
  | '/Process1/Process1Execution'
  | '/Process1/Process1Fin'
  | '/Process1/Process1LeverReserve2'
  | '/Process1/Process1LeverReserveForme'
  | '/Process1/Process1RefusDepot'
  | '/Process1/Process1RefusEncaissement'

  | '/Process2/Process2EmailEnvoye'
  | '/Process2/Process2EnregistrementDemande'
  | '/Process2/Process2ExaminerFond'
  | '/Process2/Process2ImmatriculationProvisoire'
  | '/Process2/Process2PréparerImmatriculation'
  | '/Process2/Process2RejetProvisoire'

  | '/Process3/Process3EmissionCC14'
  | '/Process3/Process3EnregistrementDemande'
  | '/Process3/Process3EtablissementCC20'
  | '/Process3/Process3EtablissementPR14'
  | '/Process3/Process3FinProcessus'
  | '/Process3/Process3PublicationPR14'
  | '/Process3/Process3TransmissionPR14'
  | '/Process3/Process3TypeChangement'
  | '/Process3/Process3VerificationForme'
  | '/Process3/Process3Notifier'



  fileRoutesByTo: FileRoutesByTo
  to:
  | '/'
  | '/Process1/Process1DepotDemand'
  | '/Process1/Process1EncaissementTaxe'
  | '/Process1/Process1Execution'
  | '/Process1/Process1Fin'
  | '/Process1/Process1LeverReserve2'
  | '/Process1/Process1LeverReserveForme'
  | '/Process1/Process1RefusDepot'
  | '/Process1/Process1RefusEncaissement'

  | '/Process2/Process2EmailEnvoye'
  | '/Process2/Process2EnregistrementDemande'
  | '/Process2/Process2ExaminerFond'
  | '/Process2/Process2ImmatriculationProvisoire'
  | '/Process2/Process2PréparerImmatriculation'
  | '/Process2/Process2RejetProvisoire'

  | '/Process3/Process3EmissionCC14'
  | '/Process3/Process3EnregistrementDemande'
  | '/Process3/Process3EtablissementCC20'
  | '/Process3/Process3EtablissementPR14'
  | '/Process3/Process3FinProcessus'
  | '/Process3/Process3PublicationPR14'
  | '/Process3/Process3TransmissionPR14'
  | '/Process3/Process3TypeChangement'
  | '/Process3/Process3VerificationForme'
  | '/Process3/Process3Notifier'
  id:
  | '__root__'
  | '/'
  | '/Process1/Process1DepotDemand'
  | '/Process1/Process1EncaissementTaxe'
  | '/Process1/Process1Execution'
  | '/Process1/Process1Fin'
  | '/Process1/Process1LeverReserve2'
  | '/Process1/Process1LeverReserveForme'
  | '/Process1/Process1RefusDepot'
  | '/Process1/Process1RefusEncaissement'

  | '/Process2/Process2EmailEnvoye'
  | '/Process2/Process2EnregistrementDemande'
  | '/Process2/Process2ExaminerFond'
  | '/Process2/Process2ImmatriculationProvisoire'
  | '/Process2/Process2PréparerImmatriculation'
  | '/Process2/Process2RejetProvisoire'

  | '/Process3/Process3EmissionCC14'
  | '/Process3/Process3EnregistrementDemande'
  | '/Process3/Process3EtablissementCC20'
  | '/Process3/Process3EtablissementPR14'
  | '/Process3/Process3FinProcessus'
  | '/Process3/Process3PublicationPR14'
  | '/Process3/Process3TransmissionPR14'
  | '/Process3/Process3TypeChangement'
  | '/Process3/Process3VerificationForme'
  | '/Process3/Process3Notifier'

  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  '/Process1/Process1DepotDemand': typeof Process1Process1DepotDemandRoute
  '/Process1/Process1EncaissementTaxe': typeof Process1Process1EncaissementTaxeRoute
  '/Process1/Process1Execution': typeof Process1Process1ExecutionRoute
  '/Process1/Process1Fin': typeof Process1Process1FinRoute
  '/Process1/Process1LeverReserve2': typeof Process1Process1LeverReserve2Route
  '/Process1/Process1LeverReserveForme': typeof Process1Process1LeverReserveFormeRoute
  '/Process1/Process1RefusDepot': typeof Process1Process1RefusDepotRoute
  '/Process1/Process1RefusEncaissement': typeof Process1Process1RefusEncaissementRoute

  '/Process2/Process2EmailEnvoye': typeof Process2Process2EmailEnvoyeRoute
  '/Process2/Process2EnregistrementDemande': typeof Process2Process2EnregistrementDemandeRoute
  '/Process2/Process2ExaminerFond': typeof Process2Process2ExaminerFondRoute
  '/Process2/Process2ImmatriculationProvisoire': typeof Process2Process2ImmatriculationProvisoireRoute
  '/Process2/Process2PréparerImmatriculation': typeof Process2Process2PréparerImmatriculationRoute
  '/Process2/Process2RejetProvisoire': typeof Process2Process2RejetProvisoireRoute

  '/Process3/Process3EmissionCC14': typeof Process3Process3EmissionCC14Route
  '/Process3/Process3EnregistrementDemande': typeof Process3Process3EnregistrementDemandeRoute
  '/Process3/Process3EtablissementCC20': typeof Process3Process3EtablissementCC20Route
  '/Process3/Process3EtablissementPR14': typeof Process3Process3EtablissementPR14Route
  '/Process3/Process3FinProcessus': typeof Process3Process3FinProcessusRoute
  '/Process3/Process3PublicationPR14': typeof Process3Process3PublicationPR14Route
  '/Process3/Process3TransmissionPR14': typeof Process3Process3TransmissionPR14Route
  '/Process3/Process3TypeChangement': typeof Process3Process3TypeChangementRoute
  '/Process3/Process3VerificationForme': typeof Process3Process3VerificationFormeRoute
  '/Process3/Process3Notifier': typeof Process3Process3NotifierRoute


}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Process1Process1DepotDemandRoute: Process1Process1DepotDemandRoute,
  Process1Process1EncaissementTaxeRoute: Process1Process1EncaissementTaxeRoute,
  Process1Process1ExecutionRoute: Process1Process1ExecutionRoute,
  Process1Process1FinRoute: Process1Process1FinRoute,
  Process1Process1LeverReserve2Route: Process1Process1LeverReserve2Route,
  Process1Process1LeverReserveFormeRoute: Process1Process1LeverReserveFormeRoute,
  Process1Process1RefusDepotRoute: Process1Process1RefusDepotRoute,
  Process1Process1RefusEncaissementRoute: Process1Process1RefusEncaissementRoute,

  Process2Process2EmailEnvoyeRoute:
    Process2Process2EmailEnvoyeRoute,
  Process2Process2EnregistrementDemandeRoute: Process2Process2EnregistrementDemandeRoute,
  Process2Process2ExaminerFondRoute: Process2Process2ExaminerFondRoute,
  Process2Process2ImmatriculationProvisoireRoute: Process2Process2ImmatriculationProvisoireRoute,
  Process2Process2PréparerImmatriculationRoute: Process2Process2PréparerImmatriculationRoute,
  Process2Process2RejetProvisoireRoute: Process2Process2RejetProvisoireRoute,

  Process3Process3EmissionCC14Route: Process3Process3EmissionCC14Route,
  Process3Process3EnregistrementDemandeRoute: Process3Process3EnregistrementDemandeRoute,
  Process3Process3EtablissementCC20Route: Process3Process3EtablissementCC20Route,
  Process3Process3EtablissementPR14Route: Process3Process3EtablissementPR14Route,
  Process3Process3FinProcessusRoute: Process3Process3FinProcessusRoute,
  Process3Process3PublicationPR14Route: Process3Process3PublicationPR14Route,
  Process3Process3TransmissionPR14Route: Process3Process3TransmissionPR14Route,
  Process3Process3TypeChangementRoute: Process3Process3TypeChangementRoute,
  Process3Process3VerificationFormeRoute: Process3Process3VerificationFormeRoute,
  Process3Process3NotifierRoute: Process3Process3NotifierRoute,

}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/Maj11/Maj11MutEnregistrerDemande",
        "/Maj11/Maj11MutEnregistrerDepot",
        "/Maj11/Maj11MutExaminerEdd",
        "/Maj11/Maj11MutPayerPenaliteRejet",
        "/Maj11/Maj11PubChoix",
        "/Maj11/Maj11PubEncaisserTax",
        "/Maj11/Maj11PubEnregRejet",
        "/Maj11/Maj11PubEnregistrerRefus",
        "/Maj11/Maj11PubExaminerFond",
        "/Maj11/Maj11PubExecuterFin",
        "/Maj11/Maj11PubLeverReserve",
        "/Maj11/Maj11PubLeverReserveBackground",
        "/Maj3/Maj3MutTotalCreerDossier",
        "/Maj3/Maj3MutTotalEnregRejet",
        "/Maj3/Maj3MutTotalExaminerFond",
        "/Maj3/Maj3MutTotalLeverReserve",
        "/Maj3/Maj3MutTotalPayerDroits",
        "/Maj3/Maj3MutTotalPayerPenalite",
        "/Maj3/Maj3MutTotalPublierActe",
        "/Maj3/Maj3MutTotalRedigierProjetActe"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/Maj11/Maj11MutEnregistrerDemande": {
      "filePath": "Maj11/Maj11MutEnregistrerDemande.tsx"
    },
    "/Maj11/Maj11MutEnregistrerDepot": {
      "filePath": "Maj11/Maj11MutEnregistrerDepot.tsx"
    },
    "/Maj11/Maj11MutExaminerEdd": {
      "filePath": "Maj11/Maj11MutExaminerEdd.tsx"
    },
    "/Maj11/Maj11MutPayerPenaliteRejet": {
      "filePath": "Maj11/Maj11MutPayerPenaliteRejet.tsx"
    },
    "/Maj11/Maj11PubChoix": {
      "filePath": "Maj11/Maj11PubChoix.tsx"
    },
    "/Maj11/Maj11PubEncaisserTax": {
      "filePath": "Maj11/Maj11PubEncaisserTax.tsx"
    },
    "/Maj11/Maj11PubEnregRejet": {
      "filePath": "Maj11/Maj11PubEnregRejet.tsx"
    },
    "/Maj11/Maj11PubEnregistrerRefus": {
      "filePath": "Maj11/Maj11PubEnregistrerRefus.tsx"
    },
    "/Maj11/Maj11PubExaminerFond": {
      "filePath": "Maj11/Maj11PubExaminerFond.tsx"
    },
    "/Maj11/Maj11PubExecuterFin": {
      "filePath": "Maj11/Maj11PubExecuterFin.tsx"
    },
    "/Maj11/Maj11PubLeverReserve": {
      "filePath": "Maj11/Maj11PubLeverReserve.tsx"
    },
    "/Maj11/Maj11PubLeverReserveBackground": {
      "filePath": "Maj11/Maj11PubLeverReserveBackground.tsx"
    },
    "/Maj3/Maj3MutTotalCreerDossier": {
      "filePath": "Maj3/Maj3MutTotalCreerDossier.tsx"
    },
    "/Maj3/Maj3MutTotalEnregRejet": {
      "filePath": "Maj3/Maj3MutTotalEnregRejet.tsx"
    },
    "/Maj3/Maj3MutTotalExaminerFond": {
      "filePath": "Maj3/Maj3MutTotalExaminerFond.tsx"
    },
    "/Maj3/Maj3MutTotalLeverReserve": {
      "filePath": "Maj3/Maj3MutTotalLeverReserve.tsx"
    },
    "/Maj3/Maj3MutTotalPayerDroits": {
      "filePath": "Maj3/Maj3MutTotalPayerDroits.tsx"
    },
    "/Maj3/Maj3MutTotalPayerPenalite": {
      "filePath": "Maj3/Maj3MutTotalPayerPenalite.tsx"
    },
    "/Maj3/Maj3MutTotalPublierActe": {
      "filePath": "Maj3/Maj3MutTotalPublierActe.tsx"
    },
    "/Maj3/Maj3MutTotalRedigierProjetActe": {
      "filePath": "Maj3/Maj3MutTotalRedigierProjetActe.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
